[[mgr.prepend_keymap]]
on   = "Q"
run  = 'quit'

[[mgr.prepend_keymap]]
on   = "q"
run  = 'quit --no-cwd-file'

[[mgr.prepend_keymap]]
on   = "m"
run  = 'cd /mnt'

[[mgr.prepend_keymap]]
on   = "H"
run  = 'cd /home/vukani'

[[mgr.prepend_keymap]]
on   = "C"
run  = 'cd /home/vukani/.dotfiles'

[[mgr.prepend_keymap]]
on   = "W"
run  = 'shell --orphan -- set-wallpaper.sh %h'
desc = "Set as wallpaper"
